kind: OperatorGroup
apiVersion: operators.coreos.com/v1
metadata:
  name: openshift-vertical-pod-autoscaler
  namespace: openshift-vertical-pod-autoscaler
spec:
  targetNamespaces:
    - openshift-vertical-pod-autoscaler
